sudo: false
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

install:
    - source ./install-dependencies.sh

script:
    - pushd src && opp_makemake -f --deep --make-so -I$INET/src -I$INET/src/inet/common -I.. -KINET_PROJ=$INET && popd
    - make -j2
    - export RUN=5
    - export REP=0
    - opp_run -r $RUN --seed-set=$REP --repeat=1 --cmdenv-express-mode=true --vector-recording=false -u Cmdenv -c DSME -n simulations:src:$INET/examples:$INET/src -l $INET/src/INET -l src/inet-dsme --debug-on-errors=false simulations/omnetpp.ini

cache:
    directories:
    - omnetdownload
    - omnetpp-5.0
    - inet
