sudo: false
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

install:
  - source ./install-dependencies.sh

script:
  - pushd src && opp_makemake -f --deep --make-so -I$INET/src -I$INET/src/inet/common -I.. -KINET_PROJ=$INET && popd
  - make -j2
  #- ./ci_test.sh
  - mkdir -p results
  - utils/ci_to_jekyll.py results

cache:
  directories:
  - omnetdownload
  - omnetpp-5.0
  - inet

