sudo: false
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libav-tools
    - python-numpy
    - python-tk
    - libavcodec-extra-53

before_install:
  - pip install --user `whoami` matplotlib
  - openssl aes-256-cbc -K $encrypted_ea54299d5f4f_key -iv $encrypted_ea54299d5f4f_iv -in utils/publish_key.enc -out ~/.ssh/publish_key -d
  - chmod u=rw,og= ~/.ssh/publish_key
  - echo "Host github.com" >> ~/.ssh/config
  - echo "  IdentityFile ~/.ssh/publish_key" >> ~/.ssh/config
  - cat ~/.ssh/config

install:
  - source ./install-dependencies.sh

script:
  - ./build.sh $INET
  - ./ci_test.sh $INET
  - echo "Test" > results/index.md
  - ./utils/gts_allocation.py --no-show -l results/DSME-mac.log -o results/gts_allocation.mp4
  - rm results/DSME-mac.log # too large to store
  - utils/ci_to_jekyll.py results

cache:
  directories:
  - omnetdownload
  - omnetpp-5.0
  - inet

