sudo: false
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_install:
  - openssl aes-256-cbc -K $encrypted_ea54299d5f4f_key -iv $encrypted_ea54299d5f4f_iv -in utils/publish_key.enc -out ~/.ssh/publish_key -d
  - chmod u=rw,og= ~/.ssh/publish_key
  - echo "Host github.com" >> ~/.ssh/config
  - echo "  IdentityFile ~/.ssh/publish_key" >> ~/.ssh/config
  - cat ~/.ssh/config

install:
  - source ./install-dependencies.sh

script:
  - pushd src && opp_makemake -f --deep --make-so -I$INET/src -I$INET/src/inet/common -I.. -KINET_PROJ=$INET && popd
  - make -j2
  - mkdir -p results
  - ./ci_test.sh $INET
  - echo "Test" > results/index.md
  - utils/ci_to_jekyll.py results

cache:
  directories:
  - omnetdownload
  - omnetpp-5.0
  - inet

