name: webplot
version: 1.0.0
author: Maximilian Köstler 
environment:
    sdk: '>=0.8.10+6 <2.0.0'
dependencies:
    browser: ^0.10.0
    wamp: ^0.4.3
    chartjs: ^0.2.0+1
    angular2: 2.0.0-beta.21
    dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
